cmake_minimum_required(VERSION 3.10)

# Nom du projet
project(MiniAmazon)

# Version du C++
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

# Inclure les headers (.h)
inclu
de_directories(include)

# Création de l'exécutable
add_executable(MiniAmazon
    src/main.cpp
    src/Produit.h
    src/Panier.cpp
    src/MiniAMAZON.cpp
)











































